from playwright.sync_api import Page, expect


def test_authentication(page: Page):
    page.goto('https://the-internet.herokuapp.com/')
    page.get_by_role('link', name='Form Authentication').click()
    username_field = page.get_by_role('textbox', name='Username')
    password_field = page.get_by_role('textbox', name='Password')
    username_field.fill('test')
    password_field.fill('user77')
    page.get_by_role('button', name='Login').click()


def test_fill_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    firstname = page.get_by_placeholder('First Name')
    firstname.fill('AprilUser')
    lastname = page.get_by_role('textbox', name='Last Name')
    lastname.fill('160424')
    email = page.get_by_placeholder('name@example.com')
    email.fill('apriltest@user.comx')
    other_radio_button = page.locator('label[for="gender-radio-3"]')
    other_radio_button.check()
    mobile_number = page.get_by_role('textbox', name='Mobile Number')
    mobile_number.fill('+111223232313')
    date_of_birth_input = page.locator('#dateOfBirthInput')
    date_of_birth_input.fill('1 Jul 2005')
    date_of_birth_input.press('Enter')
    page.fill("#subjectsInput", "Computer Science")
    page.press("#subjectsInput", "Enter")
    reading_checkbox = page.locator('label[for="hobbies-checkbox-2"]')
    reading_checkbox.check()
    current_address = page.get_by_placeholder('Current Address')
    current_address.fill('Testovaya vulica')
    page.fill("#react-select-3-input", "Rajasthan")
    page.press("#react-select-3-input", "Enter")
    page.fill("#react-select-4-input", "Jaipur")
    page.press("#react-select-4-input", "Enter")
    submit_button = page.get_by_role('button', name='submit')
    submit_button.click()
